site_name: ODMantic
site_description: AsyncIO MongoDB ODM (Object Document Mapper) using python type hinting
repo_name: art049/odmantic
repo_url: https://github.com/art049/odmantic
theme:
  name: material
  palette:
    primary: light green
    accent: light green
    scheme: slate
  features:
    - instant
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
      guess_lang: false
  - markdown_include.include:
      base_path: docs/tests
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      custom_templates: docs/api_reference/templates
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true
      watch:
        - odmantic/

nav:
  - Overview: index.md
  - quickstart.md
  - fields.md
  - engine.md
  - modeling.md
  - filtering.md
  - types.md
  - hate.md
  - API Reference:
      - ./api_reference/model.md
      - ./api_reference/engine.md
      - ./api_reference/field.md
      - ./api_reference/reference.md
      - ./api_reference/exceptions.md
  - changelog.md
