site_name: ODMantic
site_description: AsyncIO MongoDB ODM (Object Document Mapper) using python type hinting
repo_name: art049/odmantic
repo_url: https://github.com/art049/odmantic
strict: true
theme:
  name: material
  palette:
    primary: light green
    accent: light green
    scheme: preference
  icon:
    logo: material/spa
  features:
    - instant
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - codehilite:
      linenums: true
      guess_lang: false
  - pymdownx.snippets:
      base_path: docs/examples_src
      check_paths: true # Fail when the document to include is not found
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji

plugins:
  - search
  - mkdocstrings:
      custom_templates: docs/api_reference/templates
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true
      watch:
        - odmantic/

nav:
  - Overview: index.md
  - quickstart.md
  - fields.md
  - modeling.md
  - engine.md
  - filtering.md
  - types.md
  - "I hate ORMs/ODMs": outside_odm.md
  - API Reference:
      - model: ./api_reference/model.md
      - engine: ./api_reference/engine.md
      - query: ./api_reference/query.md
      - field: ./api_reference/field.md
      - reference: ./api_reference/reference.md
      - exceptions: ./api_reference/exceptions.md
  - changelog.md
